import React from "react";
import CustomColor from "./CustomColor";
import CustomCover from "./CustomCover";
import CustomSwitch from "./CustomSwitch";
import ShowCase from "./ShowCase";
import CustomBackground from "./CustomBackground";
import MaskedImage from "./MaskedImage";
import HoverImage from "./HoverImage";
import AutoSwitchGallery from "./AutoSwitchGallery";
import SwitchGallery from "./SwitchGallery";

export { default as CustomColor } from "./CustomColor";
export { default as CustomCover } from "./CustomCover";
export { default as CustomSwitch } from "./CustomSwitch";
export { default as ShowCase } from "./ShowCase";
export { default as CustomBackground } from "./CustomBackground";
export { default as MaskedImage } from "./MaskedImage";
export { default as HoverImage } from "./HoverImage";
export { default as AutoSwitchGallery } from "./AutoSwitchGallery";
export { default as SwitchGallery } from "./SwitchGallery";
